# Generated by Django 4.1.3 on 2022-11-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_productos_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='stock',
        ),
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
    ]
