# Generated by Django 4.1.3 on 2022-11-16 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_productos_stock_alter_productos_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='nombre',
            new_name='producto',
        ),
    ]
